### PR TITLE
Add GeoIP database support

### PR DESCRIPTION
**Pull request by rossdonald**
Adds an option to use an IP database to lookup the server location dynamically. If the IP database file is not found FGPE will work as normal using the CSV IP list. I have not coded with python before so please correct any mistakes.

### CODE REVIEW

**Comment by notatallshaw** [comment]
Another option would to be make this a function call and use `functools.lru_cache`, I don't mind which, in fact I don't even mind the call not being cached. I just don't like the process keeping an open file handler to this database file.

**Comment by rossdonald** [comment]
Thanks for the feedback. Since the `lookup` function already has `@cache` I might just rely on that instead of adding another level of caching.

**Comment by notatallshaw** [comment]
Oh yeah perfect, I forgot that was there.

I'm going to merge the pull request, I forget if there's something specific I need to do to make it the release executable but if so that will have to wait a few days as I'm travelling right now.

**Comment by rossdonald** [comment]
Ok great, when you are ready on the main page under Releases there is "Create a new release" and put in a version number tag and it should make it for you.

**Pull request merged**
